In [14]:
import requests
import pandas as pd

from Data_Connection import get_connection

In [15]:
API_URL = "https://fakestoreapi.com/products"

response = requests.get(API_URL)

response.raise_for_status()

data = response.json()

print("API Data Extracted Successfully")

API Data Extracted Successfully

In [16]:
df = pd.DataFrame(data)

df.head()

,id,title,price,description,category,image,rating
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,Your perfect pack for everyday use and walks i...,men's clothing,https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...,"{'rate': 3.9, 'count': 120}"
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,"Slim-fitting style, contrast raglan long sleev...",men's clothing,https://fakestoreapi.com/img/71-3HjGNDUL._AC_S...,"{'rate': 4.1, 'count': 259}"
2,3,Mens Cotton Jacket,55.99,great outerwear jackets for Spring/Autumn/Wint...,men's clothing,https://fakestoreapi.com/img/71li-ujtlUL._AC_U...,"{'rate': 4.7, 'count': 500}"
3,4,Mens Casual Slim Fit,15.99,The color could be slightly different between ...,men's clothing,https://fakestoreapi.com/img/71YXzeOuslL._AC_U...,"{'rate': 2.1, 'count': 430}"
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,"From our Legends Collection, the Naga was insp...",jewelery,https://fakestoreapi.com/img/71pWzhdJNwL._AC_U...,"{'rate': 4.6, 'count': 400}"

In [17]:
df = df[
    [
        "id",
        "title",
        "price",
        "category",
        "rating"
    ]
]

df["rating"] = df["rating"].apply(lambda x: x["rate"])

df.columns = [
    "ProductID",
    "ProductName",
    "Price",
    "Category",
    "Rating"
]

df = df.drop_duplicates()

df = df.dropna()

df.head()

,ProductID,ProductName,Price,Category,Rating
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,men's clothing,3.9
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,men's clothing,4.1
2,3,Mens Cotton Jacket,55.99,men's clothing,4.7
3,4,Mens Casual Slim Fit,15.99,men's clothing,2.1
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,jewelery,4.6

In [18]:
conn = get_connection()

cursor = conn.cursor()

print("Connected Successfully")

Connected Successfully

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS fake_store.products
(
    ProductID INT,
    ProductName STRING,
    Price DOUBLE,
    Category STRING,
    Rating DOUBLE
)
""")

insert_query = """
INSERT INTO fake_store.products
VALUES (?, ?, ?, ?, ?)
"""

rows = list(df.itertuples(index=False, name=None))

cursor.executemany(insert_query, rows)

conn.commit()

print("Data Stored Successfully")

Data Stored Successfully

In [20]:
cursor.execute("""
SELECT *
FROM fake_store.products
LIMIT 10
""")

rows = cursor.fetchall()

for row in rows:
    print(row)

Row(ProductID=11, ProductName='Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5', Price=109.0, Category='electronics', Rating=4.8)
Row(ProductID=15, ProductName="BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats", Price=56.99, Category="women's clothing", Rating=2.6)
Row(ProductID=17, ProductName='Rain Jacket Women Windbreaker Striped Climbing Raincoats', Price=39.99, Category="women's clothing", Rating=3.8)
Row(ProductID=1, ProductName='Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', Price=109.95, Category="men's clothing", Rating=3.9)
Row(ProductID=9, ProductName='WD 2TB Elements Portable External Hard Drive - USB 3.0 ', Price=64.0, Category='electronics', Rating=3.3)
Row(ProductID=10, ProductName='SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s', Price=109.0, Category='electronics', Rating=2.9)
Row(ProductID=2, ProductName='Mens Casual Premium Slim Fit T-Shirts ', Price=22.3, Category="men's clothing", Rating=4.1)
Row(ProductID=7, ProductName='White Gold Plated Princess', Price=9.99, Category='jewelery', Rating=3.0)
Row(ProductID=7, ProductName='White Gold Plated Princess', Price=9.99, Category='jewelery', Rating=3.0)
Row(ProductID=3, ProductName='Mens Cotton Jacket', Price=55.99, Category="men's clothing", Rating=4.7)

In [ ]:
cursor.close()
conn.close()